#include "menu_types.h"

static const menu_id_names_t s_menu_items[] = {
    [MENU_ID_ROOT] = {MENU_ID_ROOT, "MENU_ID_ROOT"},
    [MENU_ID_START] = {MENU_ID_START, "MENU_ID_START"},
    [MENU_ID_REGIMES] = {MENU_ID_REGIMES, "MENU_ID_REGIMES"},
    [MENU_ID_VERSION] = {MENU_ID_VERSION, "MENU_ID_VERSION"},
    [MENU_ID_SETTINGS] = {MENU_ID_SETTINGS, "MENU_ID_SETTINGS"},
    [MENU_ID_PWM_FREQUENCY] = {MENU_ID_PWM_FREQUENCY, "MENU_ID_PWM_FREQUENCY"},
    [MENU_ID_HI_CHANNEL] = {MENU_ID_HI_CHANNEL, "MENU_ID_HI_CHANNEL"},
    [MENU_ID_HI_DELAY] = {MENU_ID_HI_DELAY, "MENU_ID_HI_DELAY"},
    [MENU_ID_HI_DURATION] = {MENU_ID_HI_DURATION, "MENU_ID_HI_DURATION"},
    [MENU_ID_HI_DUTY] = {MENU_ID_HI_DUTY, "MENU_ID_HI_DUTY"},
    [MENU_ID_HI_PWM_ON] = {MENU_ID_HI_PWM_ON, "MENU_ID_HI_PWM_ON"},
    [MENU_ID_LO_CHANNEL] = {MENU_ID_LO_CHANNEL, "MENU_ID_LO_CHANNEL"},
    [MENU_ID_LO_DELAY] = {MENU_ID_LO_DELAY, "MENU_ID_LO_DELAY"},
    [MENU_ID_LO_DURATION] = {MENU_ID_LO_DURATION, "MENU_ID_LO_DURATION"},
    [MENU_ID_LO_DUTY] = {MENU_ID_LO_DUTY, "MENU_ID_LO_DUTY"},
    [MENU_ID_LO_PWM_ON] = {MENU_ID_LO_PWM_ON, "MENU_ID_LO_PWM_ON"},
    [MENU_ID_COUNT] = {MENU_ID_COUNT, "MENU_ID_COUNT"},
};

const char *menu_types_get_name(menu_id_t id) {
    if (id >= MENU_ID_COUNT)
        return 0;
    return s_menu_items[id].name;
}